name: Generate Play Store AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Fix Execute Permission
        run: |
          cd android
          chmod +x gradlew

      - name: Fresh Clean Project
        run: |
          cd android
          bash ./gradlew clean

      - name: Build Standard Production Bundle
        run: |
          cd android
          bash ./gradlew bundleRelease --no-daemon

      - name: Upload Finished AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-production-ready
          path: android/app/build/outputs/bundle/release/*.aab
